
import __ASTRO_IMAGE_IMPORT_Z2waKis from "../../assets/blew.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpondtalk.mdx";
import __ASTRO_IMAGE_IMPORT_rHNvT from "../../assets/whale.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fapu-whale-collection.md";
import __ASTRO_IMAGE_IMPORT_1E2HY8 from "../../assets/apu-army.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fapuarmy.md";
import __ASTRO_IMAGE_IMPORT_mofUD from "../../assets/peace.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fapuvil-war.md";
import __ASTRO_IMAGE_IMPORT_1ssv0L from "../../assets/carrot.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcarrotfunding.md";
import __ASTRO_IMAGE_IMPORT_Z1Bvafq from "../../assets/greenrock-banner.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fgreenrock-q3-2025.md";
import __ASTRO_IMAGE_IMPORT_1lySEk from "../../assets/tips.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fsuccess-tips.md";
import __ASTRO_IMAGE_IMPORT_1OFt5L from "../../assets/blewstein-files.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fblewstein.md";
export default new Map([["../../assets/blew.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpondtalk.mdx", __ASTRO_IMAGE_IMPORT_Z2waKis], ["../../assets/whale.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fapu-whale-collection.md", __ASTRO_IMAGE_IMPORT_rHNvT], ["../../assets/apu-army.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fapuarmy.md", __ASTRO_IMAGE_IMPORT_1E2HY8], ["../../assets/peace.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fapuvil-war.md", __ASTRO_IMAGE_IMPORT_mofUD], ["../../assets/carrot.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcarrotfunding.md", __ASTRO_IMAGE_IMPORT_1ssv0L], ["../../assets/greenrock-banner.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fgreenrock-q3-2025.md", __ASTRO_IMAGE_IMPORT_Z1Bvafq], ["../../assets/tips.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fsuccess-tips.md", __ASTRO_IMAGE_IMPORT_1lySEk], ["../../assets/blewstein-files.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fblewstein.md", __ASTRO_IMAGE_IMPORT_1OFt5L]]);
		